### ISSUE TITLE
can it work in Python 3.7?

### ISSUE THREAD

**Issue by gitzorro** [Tishka17/aiogram_dialog#88]
Hi, first THX for the library :-)
i try to use python 3.7 and aiogram-dialog 1.0.2
If i use
`from aiogram_dialog import Dialog`
i get the error 
`ImportError: cannot import name 'Protocol' from 'typing'`
seems that on line 3 in dialog.py
`from typing import Protocol`
is used 
according to my typing.pyi - file, and some other documentation
```
# Protocol is only present in 3.8 and later, but mypy needs it unconditionally
Protocol: _SpecialForm = ...
```
Protocol needs at least python 3.8
ist there any older version that support python 3.7?

**Comment by Tishka17** [comment]
fixed in dev branch
